name: Pull Request
on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull Request index to run benchmark, ex. "12512"
        required: true
        type: string
      repeats:
        description: number of benchmark repeats
        required: true
        type: number
        default: 10
  workflow_call:
    inputs:
      pull_number:
        description: Pull Request index to run benchmark, ex. "12512"
        required: true
        type: string
      repeats:
        description: number of benchmark repeats
        required: true
        type: number
        default: 10
jobs:
  benchmark:
    name: Run benchmark
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: cd runner && pnpm install

      - name: Run benchmark
        id: run_benchmark
        run: cd runner && pnpm tsx src/cli.ts bench --pull-number="${{ inputs.pull_number }}" --repeats="${{ inputs.repeats }}"
