name: Pull Request Triggered by Comment
on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull Request number to run benchmark (e.g. 12512)
        required: true
        type: string
      repeats:
        description: number of benchmark repeats
        required: true
        type: string
        default: '10'
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      comment-id: ${{ steps.create-comment.outputs.result }}
    steps:
      - id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.PR_GITHUB_APP_ID }}
          private_key: ${{ secrets.PR_GITHUB_APP_PRIVATE_KEY }}
          repository: '${{ github.repository_owner }}/vite'
      - id: create-comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          result-encoding: string
          script: |
            const url = `${context.serverUrl}//${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            const urlLink = `[Open](${url})`
            const { data: comment } = await github.rest.issues.createComment({
              issue_number: Number(context.payload.inputs.pull_number),
              owner: context.repo.owner,
              repo: 'vite',
              body: `⏳ Triggered benchmark: ${urlLink}`
            })
            return comment.id
  execute-all:
    name: Run benchmark
    outputs:
      summary: ${{ steps.run_benchmark.outputs.summary }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: cd runner && pnpm install

      - name: Run benchmark
        id: run_benchmark
        run: cd runner && pnpm tsx src/cli.ts bench --pull-number="${{ inputs.pull_number }}" --repeats="${{ inputs.repeats }}"

  update-comment:
    runs-on: ubuntu-latest
    needs: [init, execute-all]
    if: always()
    steps:
      - id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.PR_GITHUB_APP_ID }}
          private_key: ${{ secrets.PR_GITHUB_APP_PRIVATE_KEY }}
          repository: '${{ github.repository_owner }}/vite'
      - uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { data: { jobs } } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              per_page: 100
            });

            const result = jobs
              .filter(job => job.name.startsWith('execute-all'))
              .map(job => {
                return { conclusion: job.conclusion, link: job.html_url }
              })

            const url = `${context.serverUrl}//${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            const urlLink = `[Open](${url})`

            const summary = `${{ needs.execute-all.outputs.summary }}`
            console.log('summary', summary)

            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: 'vite',
              comment_id: ${{ needs.init.outputs.comment-id }},
              body: summary
            })
